### ISSUE TITLE
Unable to load the plugin

### ISSUE THREAD

**Issue by HYDeath** [TheSilentPro/HeadDB#12]
Core: paper 1.16.5
Java:openjdk version "1.8.0_292"
log:
[log.txt](https://github.com/TheSilentPro/HeadDB/files/6758608/log.txt)

**Comment by HYDeath** [comment]
After I talked to the original log, I personally felt that it was a network problem. I tried it locally and the problem was still there. Then I tried it with another friend of mine. There is still the same thing.

**Comment by HYDeath** [comment]
I don’t know if the author has any solution?

**Comment by joex92** [comment]
Got this problem on purpur-1.17.1 it was working fine, suddenly on restart in just couldn't keep loading, the server hung loading the plugin: #19
