### ISSUE TITLE
Plugin loads forever

### ISSUE THREAD

**Issue by joex92** [TheSilentPro/HeadDB#19]
**Describe the bug**
The plugin was working fine, then after restarting half an hour ago before posting this the server just couldn't keep loading, it just stayed at `Loading HeadDB`... then I deleted HeadDB and the server kept going... 

**Information**
Plugin Version: 2.4.3
Server Version: Purpur version git-Purpur-1385 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 529daae on ver/1.17.1)
Client Version: 1.17.1 (Fabric-0.11.6)

**Console**
```
[18:02:31] [Server thread/INFO]: [HeadDB] Enabling HeadDB v2.4.3
[18:02:31] [Server thread/INFO]: [HeadDB] [INFO]: Loading HeadDB - 2.4.3
```
It just stayed there, the CPU usage was crazy, the instant HeadDB started loading CPU percentage usage was everywhere, it went abruptly to 0% then 200% then again 0% going up and down... (using [Pterodactyl](https://pterodactyl.io))

**Comment by TheSilentPro** [comment]
Enable debug in the config and send me the logs where it freezes again

**Comment by WaterOtter86** [comment]
It load forever for me too

**Comment by WaterOtter86** [comment]
[20:02:52 INFO]: [HeadDB] Enabling HeadDB v2.4.3
[20:02:52 INFO]: [HeadDB] [INFO]: Loading HeadDB - 2.4.3
[20:02:52 INFO]: [HeadDB] [DEBUG]: Initializing Database... (SYNC)
[20:02:52 INFO]: [HeadDB] [DEBUG]: Caching heads from: alphabet

**Comment by joex92** [comment]
it doesn't load forever for me anymore, but maybe it's because of the connection between the plugin and the head database when loading? idk, sometimes some plugins can't fetch the updates info...

**Comment by TheSilentPro** [comment]
> [20:02:52 INFO]: [HeadDB] Enabling HeadDB v2.4.3 [20:02:52 INFO]: [HeadDB] [INFO]: Loading HeadDB - 2.4.3 [20:02:52 INFO]: [HeadDB] [DEBUG]: Initializing Database... (SYNC) [20:02:52 INFO]: [HeadDB] [DEBUG]: Caching heads from: alphabet

> it doesn't load forever for me anymore, but maybe it's because of the connection between the plugin and the head database when loading? idk, sometimes some plugins can't fetch the updates info...

Could have been an invalid uuid or something from the database usually gets fixed by the maintainers.
You can also try turning on asyncStartup in the config see if it helps next time.

Should probably make it fetch async too but i really don't have time for it atm.
