### ISSUE TITLE
AnvilGUI compiled with different JDK

### ISSUE THREAD

**Issue by skyeredwood** [TheSilentPro/HeadDB#21]
**Describe the bug**
It seems the Anvil GUI library you're using is compiled using a different JDK version which causes an error.

**Information**
Plugin Version: 2.4.4
Server Version: 1.16.5
Client Version: 1.16.5 (although it's a server side error)

**Errors**
[click me uwu](https://sourceb.in/H1WHZCjPKS)

**Comment by TheSilentPro** [comment]
Switch to Java 16. You're using java 8 atm

**Comment by skyeredwood** [comment]
The Spigot page says that the plugin is compatible with 1.16 and that doesn't support Java 16 - please either make it Java 8 compatible or list it correctly as incompatible with <1.17.

**Comment by TheSilentPro** [comment]
> The Spigot page says that the plugin is compatible with 1.16 and that doesn't support Java 16 - please either make it Java 8 compatible or list it correctly as incompatible with <1.17.

What? You're mixing minecraft version with java version here.
You need to change your servers JAVA version to 16 (some hosts put you on java 8 if you are using a shared host).

**Comment by skyeredwood** [comment]
Apologies, misunderstood some information I saw in the 1.17 patch notes. Will update Java version :)
