### ISSUE TITLE
Favorites heads are not adding up but overwriting itself

### ISSUE THREAD

**Issue by Lemon553311-dev** [TheSilentPro/HeadDB#22]
**Describe the bug**
When adding favorites it will overwrite the first favorite slot rather than add new ones. refer to the video attached

**Information**
Plugin Version: 2.4.5
Server Version: paper build #105 1.18.1
Client Version: 1.18.1

**Errors**
There are no errors returned

**Screenshots**

https://user-images.githubusercontent.com/60439353/147569605-bbf03166-08e0-4245-a169-f1ad9a86f2d3.mp4

**Comment by TheSilentPro** [comment]
Will be fixed in 3.0 since im planning to rewrite the storage and how favorites are saved. (working on it already)

**Comment by TheSilentPro** [comment]
Should  be fixed in [3.0.0](https://github.com/TheSilentPro/HeadDB/releases/tag/3.0.0)
