### ISSUE TITLE
Text format issue

### ISSUE THREAD

**Issue by ThijmenGThN** [TheSilentPro/HeadDB#23]
**Describe the bug**
I've just installed your plugin, it's absolutely wonderful. However, I'm facing an issue in chat, is this something that could be fixed?

**Information**
Plugin Version: 3.0.1
Server Version: 1.18.1
Client Version: 1.18.1

**Errors**
No errors in console.

**Screenshots**
![image](https://user-images.githubusercontent.com/54316157/148699673-d7b3ad84-4fa9-4983-bb41-924b62f257d8.png)

**Comment by TheSilentPro** [comment]
I will fix this first thing tomorrow. Thank you!

**Comment by ThijmenGThN** [comment]
Absolutely wonderful, you're amazing!

**Comment by TheSilentPro** [comment]
Should be fixed in 3.0.2 you can find it on [Spigot](https://www.spigotmc.org/resources/free-headdb-head-menu.84967/) or the [Releases Page](https://github.com/TheSilentPro/HeadDB/releases/tag/3.0.2)
Let me know if you find another one.
