### ISSUE TITLE
/hdb command not working

### ISSUE THREAD

**Issue by Loofn** [TheSilentPro/HeadDB#24]
**Describe the bug**
/hdb command is not working, it gives out "An internal error occured"

**Information**
Plugin Version:  3.2.0
Server Version: Paper-198 (1.18.1)
Client Version:  1.18.1

**Errors**
https://paste.trixxie.dev/kcCaISwiwo

**Screenshots**
![](https://i.imgur.com/GW5iyzs.png)

**Comment by TheSilentPro** [comment]
fixed in [3.2.1](https://github.com/TheSilentPro/HeadDB/releases/tag/3.2.1)
