### ISSUE TITLE
Jar was built using Java 16, intended?

### ISSUE THREAD

**Issue by Derkades** [TheSilentPro/HeadDB#29]
It looks like the jar uploaded to jitpack requires java 16 or includes a library that requires java 16:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.2.4:shade (default-cli) on project ServerSelectorX: Error creating shaded jar: Problem shading JAR /home/robin/.m2/repository/com/github/TheSilentPro/HeadDB/4.2.0/HeadDB-4.2.0.jar entry net/wesjd/anvilgui/version/Wrapper1_17_R1.class: java.lang.IllegalArgumentException: Unsupported class file major version 60 -> [Help 1]
```

In pom.xml compilation target is set to java 9: https://github.com/TheSilentPro/HeadDB/blob/417036e5186c3d3cf36146c32a283881f03fb0b2/pom.xml#L90-L91

**Comment by TheSilentPro** [comment]
Yes, this is intended. However, I have forgotten to update the pom.
Should be updated in [4.2.1](https://github.com/TheSilentPro/HeadDB/releases/tag/4.2.1)

**Comment by Derkades** [comment]
Thanks for the clarification
