### ISSUE TITLE
403 Response (Failed to fetch heads)

### ISSUE THREAD

**Issue by davidmvos** [TheSilentPro/HeadDB#31]
**Description**
The head database plugin says "`Failed to fetch heads for category`" (E.g. "`Failed to fetch heads for decoration`"). I'll create a pastebin.

**Information**
Plugin Version: 4.4.2
Server Version: (Paper) 1.17.1 Paper git-Paper-409

**Errors**
https://paste.md-5.net/uruyavuvus.md

_This might be useful:_
I made a request from the server command line with `wget` to the minecraft-heads.com api (`wget https://minecraft-heads.com/scripts/api.php?cat=humans&tags=true`) and here is the response: 
(https://paste.md-5.net/raw/eniwakikuy)
```
--2022-05-09 17:03:23--  

https://minecraft-heads.com/scripts/api.php?cat=humans

Resolving minecraft-heads.com (minecraft-heads.com)... 172.67.141.148, 104.21.46.195, 2606:4700:3035::6815:2ec3, ...

Connecting to minecraft-heads.com (minecraft-heads.com)|172.67.141.148|:443... connected.

HTTP request sent, awaiting response... 403 Forbidden

2022-05-09 17:03:23 ERROR 403: Forbidden.
```

**Comment by GhostIsBeHere** [comment]
I can confirm this

**Comment by davidmvos** [comment]
I’ve found something interesting: When opening the site on a browser, there is the cloudflare ddos protection thing, before it redirects you.

**Comment by TheSilentPro** [comment]
The API had some issues, they should be resolved by now. That's the plugin using a backup site I made to fetch the heads.
As far as i know the api doesn't have that kind of cloudflare redirects. 
That's a 403 response though idk why it would forbid it. I'll take a better look into it today.

Sorry for the late response I didn't notice the issue.

**Comment by TheSilentPro** [comment]
The api had some issues those days. Should be working fine now and i updated the fallback service with more up-tp-date heads.
