### ISSUE TITLE
Changing the menu main message breaks the plugin

### ISSUE THREAD

**Issue by Cruwzky** [TheSilentPro/HeadDB#32]
**Describe the bug**
If you change the messages.yml file under menu -> main it breaks the plugin and lets everybody take all the heads out of the menu.

**Information**
Plugin Version: 4.4.3
Server Version: 1.18.2
Client Version: 1.18.2

**Errors**
There are no errors in the console.

**Screenshots**
See attached screen of the GUI with this bug present. I have added the text "test". And are able to take all the heads and panels from the GUI. I can do this as many time I wish.

![image](https://user-images.githubusercontent.com/20445289/170387989-0921800e-9582-42c6-82d7-4fa4423e6524.png)

**Comment by Cruwzky** [comment]
This issue is also present if you change any of the menu buttons message. This does however not break the GUI completely. It just makes so that button specific does not work.

**Comment by TheSilentPro** [comment]
Do sub-categories break? If you change the name under menu -> category do categories still work as expected (can you get heads from them?)
Do any other of the messages under `menu` break anything or just this one?

Also are you able to join the discord for easier communication? https://discord.com/invite/RJsVvVd

**Comment by Cruwzky** [comment]
Hi Silent,

I wrote to you in the Discord support.
