### ISSUE TITLE
unable to connect to minecraftheads

### ISSUE THREAD

**Issue by Ijdtm7** [TheSilentPro/HeadDB#33]
**Describe the bug**
The Plugin is unable to fetch heads from minecraftheads and uses the fallback provider instead

**Information**
Plugin Version: 4.4.3
Server Version: purpur 1.17.1
Client Version: 1.17.1

**Errors**
Provide any **relevant** errors that occur in the console. Use [pastebin](https://pastebin) or [hastebin](https://paste.md-5.net)
https://pastebin.com/5AHSJMNN

**Screenshots**

**Comment by TheSilentPro** [comment]
Not a bug, the api might be down sometimes and it will use that fallback provider.
