### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Zoleeee** [TheSilentPro/HeadDB#34]
**Describe the bug**

**Information**
Plugin Version: HeadDB-4.4.3
Server Version: 1.18.2
Client Version: 1.18.2

**Errors**
https://pastebin.com/zfhbbpiY
**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://imgur.com/a/ZQ7pPRc)

**Comment by Zoleeee** [comment]
and https://pastebin.com/14pugFi9 this bug

**Comment by TheSilentPro** [comment]
i need the error that is shown when you start the server
send me your full console log
