### ISSUE TITLE
Error on server startup

### ISSUE THREAD

**Issue by hnwh224** [TheSilentPro/HeadDB#37]
**Describe the bug**
Plugin does not load.

**Information**
Plugin Version: v4.4.4
Server Version: Purpur 1.19.2
Client Version: 1.19.2

**Errors**
https://pastebin.com/Mx0kk32H

**Comment by isaaclepes** [comment]
Came here for the same error.  After looking closely, it says the loading playerdata had an error, so I tried renaming the plugins/HeadDB/ directory to HeadDB.old.  It regenerated the config, but the error is now gone.
