### ISSUE TITLE
Permissions are not working

### ISSUE THREAD

**Issue by Lemon553311-dev** [TheSilentPro/HeadDB#43]
**Describe the bug**
Issue: player report that when running /hdb gives output of no permission but the permission is granted (please see screenshot of luckperms here:)
![image](https://user-images.githubusercontent.com/60439353/210007326-c5f6dcab-9591-4b05-9910-03edd5d2ecbd.png)
this is under the default group (everyone gets these permissions)
I even gave these permission DIRECTLY to player and it still doesnt work...

**Information**
Plugin Version: Running HeadDB - 5.0.0-rc.2
Server Version: Paper 1.19.2 (This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25))
Client Version: 1.19.2 (Lunar Client sodium)

**Errors**
Provide any **relevant** errors that occur in the console. Use [pastebin](https://pastebin) or [hastebin](https://paste.md-5.net)
There are no errors (other than "You have no permission")

**Screenshots**

**Comment by TheKrafter** [comment]
Hey, @Lemon553311-dev this seems to still be an issue in 5.0.0-rc8.

**Comment by TheSilentPro** [comment]
> Hey, @Lemon553311-dev this seems to still be an issue in 5.0.0-rc8.

The permissions format got changed to headdb.command.[name]

**Comment by TheKrafter** [comment]
> The permissions format got changed to headdb.command.[name]

Well then please update [your wiki](https://headdb.pages.dev/permissions).

I'd appreciate if you let me know here when you've done so.
