### ISSUE TITLE
HeadDB categories no longer working with custom language file

### ISSUE THREAD

**Issue by socksprox** [TheSilentPro/HeadDB#46]
**Describe the bug**
I am using a Plugin called Triton to translate everything on my server. So I created a custom language file for HeadDB, it works fine besides categories. It just says "No heads found, try again!". 

**Information**
Plugin Version: 4.17.0
Server Version: Current: git-Purpur-1886 (MC: 1.19.3)
Client Version: 1.19.3

**Errors**
Provide any **relevant** errors that occur in the console. Use [pastebin](https://pastebin) or [hastebin](https://paste.md-5.net)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/36358673/217527010-28b7247a-c895-49c8-92b7-188064004c8a.png)

**Translation file**
https://paste.gg/p/anonymous/9737fb0dfdaa41ffab1f68aaa1fa29ab

**Comment by TheSilentPro** [comment]
You're using the paid plugin, wrong github.
