### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by EthanTheFrancaboo** [TheSilentPro/HeadDB#47]
**Describe the bug**
Search function doesn't work

**Information**
Plugin Version: 5.0.0-rc3
Server Version: Paper 1.19.4
Client Version: Forge 1.19.4

**Errors**
None

**Screenshots**
Not applicable

**Comment by EthanTheFrancaboo** [comment]
If you click the search sign, it does nothing. You click it and you just stay on the headdb menu.

**Comment by EthanTheFrancaboo** [comment]
Also, 5.0.0-rc.3, my mistake

**Comment by FractalingCoder** [comment]
I have the same issue, 1.19.3 the search sign works fine, but switching to 1.19.4 breaks it

**Comment by TheSilentPro** [comment]
Should be fixed in latest spigot update (5.0.0-rc.4)

**Comment by Garyyy77** [comment]
im using the latestest version (5.0.0-rc.6) in 1.20.1 and using the command works too, but clicking on the sign does not

**Comment by TheSilentPro** [comment]
Known issue, working on a fix
