### ISSUE TITLE
Suggestion: allow changing category head IDs in config

### ISSUE THREAD

**Issue by WhoAteMyButter** [TheSilentPro/HeadDB#5]
The heads shown as the icon for the categories in /hdb should be changeable in the config.
A good idea would be to have the config ship with a default value, and use a question mark head as a backup.
People can then change this value in the config and change the categories head icon.

**Comment by TheSilentPro** [comment]
This was the original plan but i forgot about it lol.
Customization is definitely something that the plugin really lacks as of now.
