### ISSUE TITLE
Can't open Local Heads

### ISSUE THREAD

**Issue by Leg0shii** [TheSilentPro/HeadDB#53]
**Describe the bug**
I open up the skull GUI by using /skull. When pressing on the compass (local heads), nothing happens.

**Information**
Plugin Version: HeadDB v5.0.0-rc.7
Server Version: Paper 1.20.1
Client Version:  Fabric 1.20

**Errors**
(https://paste.md-5.net/winekayuro.pl)

**Comment by TheSilentPro** [comment]
should be fixed in latest update. Download again from spigot.

**Comment by TheSilentPro** [comment]
*spigot it being a bitch and not letting me post the update, download it from github releases instead*
