### ISSUE TITLE
Getting unknown warn in console

### ISSUE THREAD

**Issue by C-olossal** [TheSilentPro/HeadDB#55]
At seemingly random intervals the console for our server gets a warn from HEADDB:

**Information**
Plugin Version:  HeadDB - 5.0.0-rc.7
Server Version: Paper 1.20.1
Client Version: Fabric 1.20.1

**Errors**
(https://pastebin.com/TxX86Jk9)

**Screenshots**

**Comment by non-ke** [comment]
This issue is same as https://github.com/TheSilentPro/HeadDB/issues/54

**Comment by TheSilentPro** [comment]
Should be done in newest release, check spigot.
