### ISSUE TITLE
Question/Bug: When I add "local: 100" below "economy:" it doesn't seem to work?

### ISSUE THREAD

**Issue by SamGamerYT** [TheSilentPro/HeadDB#59]
**Describe the bug**
When I add "local: 100" below "economy:" it doesn't seem to work?

`
# Economy Options
economy:
  enabled: true
  provider: "VAULT" # Supported: VAULT
  format: "##.##"
  cost:
    alphabet: 100
    animals: 100
    blocks: 100
    decoration: 100
    food-drinks: 100
    humans: 100
    humanoid: 100
    miscellaneous: 100
    monsters: 100
    plants: 100
    local: 100`

**Information**
Plugin Version: 5.0.0-rc.7
Server Version: git-purpur-2023 (Version: 1.20.1)
Client Version: 1.20.2 Optifine

**Errors**
Doesn't charge "$100" vault currency

**Screenshots**

**Comment by TheSilentPro** [comment]
Local heads can't have a cost **yet**, only the regular head categories.
