### ISSUE TITLE
Missing Skull data

### ISSUE THREAD

**Issue by PlayGlowCraft** [TheSilentPro/HeadDB#60]
**Describe the bug**
 Found inconsistent skull meta error floods console and lags server

**Information**
Plugin Version:  5.0.0-rc.7
Server Version: This server is running Paper version git-Paper-259 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 5bb30ce)
You are 7 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-241 (MC: 1.20.2)
Client Version: Various clients involved

**Errors**
https://pastebin.com/RM7935kQ

**Screenshots**

**Comment by TheSilentPro** [comment]
Should be done in newest release, check spigot.
