### ISSUE TITLE
Add 1.20.2 support

### ISSUE THREAD

**Issue by Parthodys** [TheSilentPro/HeadDB#61]
**Describe the bug**
Internal error on 1.20.2 when opening menus. /hdb help works though.

**Information**
Plugin Version: HeadDB 5.0.0-rc.7
Server Version: git-Paper-249 (MC: 1.20.2)
Client Version: 1.20.2

**Errors**
[https://pastebin.com/Fiti2iNL](https://pastebin.com/Fiti2iNL)

**Comment by TheSilentPro** [comment]
Should be done in newest release, check spigot.
