### ISSUE TITLE
Meta warning

### ISSUE THREAD

**Issue by pro9code** [TheSilentPro/HeadDB#63]
**Describe the bug**
lots of warnings

**Information**
Plugin Version: 5.0.0-rc.8
Server Version: 1.20.2 canvasmc
Client Version: builders refuge

**Errors**
[06:19:33 WARN] [Minecraft]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).

**Screenshots**

**Comment by TheSilentPro** [comment]
Are you sure you are using rc8? Type /hdb info and show a screenshot.
Whats canvasmc, a spigot fork
?

**Comment by pro9code** [comment]
https://github.com/CraftCanvasMC/Canvas
[image: image.png]

**Comment by pro9code** [comment]
![Screenshot 2023-09-14 135734](https://github.com/TheSilentPro/HeadDB/assets/125939648/4cd0a704-7628-472d-bbff-792ffd4ac670)

**Comment by pro9code** [comment]
![image](https://github.com/TheSilentPro/HeadDB/assets/125939648/021a4142-0a50-4684-aee5-7d1ac218d1c3)

**Comment by TheSilentPro** [comment]
fixed in latest version
