### ISSUE TITLE
Head is not given to the player when buying

### ISSUE THREAD

**Issue by Parthodys** [TheSilentPro/HeadDB#69]
**Describe the bug**
When you buy a head from the menu for $$$, you don't actually receive it. Its weird and normally the item should come to your inventory.

**Information**
Plugin Version: 5.0.0-rc.8
Server Version: 1.20.2 Paper
Client Version: 1.20.2-4

**Errors**
No error when buying a head, but got spammed quite a few of these before: https://pastebin.com/1kMpksXg

**Screenshots**
Bought many heads according to chat, but received none.
![image](https://github.com/TheSilentPro/HeadDB/assets/1515422/64adc669-b203-4825-b9bd-d4bbe31374fd)

**Comment by Parthodys** [comment]
This seems to only happen when the economy cost is enabled.

**Comment by TheSilentPro** [comment]
Fixed in rc.9 latest on spigot
