### ISSUE TITLE
Search doesn't work in 1.20.4

### ISSUE THREAD

**Issue by AleFunky** [TheSilentPro/HeadDB#70]
**Describe the bug**
Searching in 1.20.4 doesn't work and throws the error in the pastebin link.

**Information**
Plugin Version: 5.0.0-rc.9
Server Version: Paper 1.20.4
Client Version: 1.20.1 (via version)

**Errors**
https://pastebin.com/g5ajcJHD

**Comment by l3nnartt** [comment]
fixed with #74 , can be closed
