### ISSUE TITLE
On every command 

### ISSUE THREAD

**Issue by notonecz** [TheSilentPro/HeadDB#71]
[14:37:13 WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).

**Comment by TheSilentPro** [comment]
Fixed in latest spigot version
