### ISSUE TITLE
Error on 1.21.

### ISSUE THREAD

**Issue by Remski01** [TheSilentPro/HeadDB#76]
**Describe the bug**
An error message ingame and the console will get sended.

**Information**
Plugin Version: v5.0.0-rc.10
Server Version: 1.21-38-master@1f5db50
Client Version: 1.21

**Errors**
https://paste.md-5.net/mabefiwuhu.bash

**Screenshots**
...

**Disclaimer:**
- I'm aware that this version is not supported. But feel like its kinda expected that the plugin will update to it.

**Comment by Parthodys** [comment]
![image](https://github.com/user-attachments/assets/cb9560f2-f7df-422b-b36e-ea346ce1024e)
Dev said this about an update

**Comment by TolisKlk** [comment]
any updates?

**Comment by Parthodys** [comment]
![image](https://github.com/user-attachments/assets/ffdf5edc-f37d-4265-a717-d9c9e2af74ee)
